# Generated by Django 5.2.7 on 2025-10-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0002_symptom_symptomoption_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(default='images/default_avatar.png', upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(default='images/default_avatar.png', upload_to='profile_pics/'),
        ),
    ]
