# Generated by Django 5.2.7 on 2025-10-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0003_doctorprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='specialty',
            field=models.CharField(choices=[('General Medicine', 'General Medicine'), ('Dermatology', 'Dermatology'), ('Orthopedics', 'Orthopedics'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology')], default='General Medicine', max_length=50),
        ),
    ]
