# Generated by Django 5.2.7 on 2025-10-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0004_helprequest_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Answered', 'Answered'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
