# Generated by Django 5.2.7 on 2025-10-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0005_alter_helprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
