# Generated by Django 5.2.7 on 2025-10-21 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomoption',
            name='next_symptom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_options', to='healthcare_app.symptom'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='healthcare_app.symptomoption'),
        ),
    ]
